### ISSUE TITLE
A case-insensitvity issue

### ISSUE THREAD

**Issue by yongjiaw** [rcongiu/Hive-JSON-Serde#104] opened 2015-03-23 20:35 UTC
I know Hive field names are case insensitive by SQL standard, so it makes sense to force all attribute names from the Json input data to lower case. However, JSON is really case sensitive, and a legal JSON input can be deemed illegal if using this SerDe. The following is an error trace from SerDeing an OpenRTB bid request in Json. The problem is that the Json data has "Osv":"8","osv":"8" twice, which is legal Json, but Hive won't be able to handle it - the only way right now is to ignore the data which is not ok for me. I don't know what should be the best solution, this is the clash between case-insensitive SQL and case sensitive Json. Would it be possible to have a SerDeProperty to only take the first value of the 'duplicate' attributes after case conversion? Or even better, is it possible to define something in the serde property so that the osv column is automatically converted to an array that can hold more than 1 values?

Diagnostic Messages for this Task:
Error: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing writable {"id":"75F78BEC-29EA-4BD9-AFDE-59248A78D2E8","imp":[{"id":"1","tagid":"114140","banner":{"w":300,"h":250,"pos":3,"topframe":1,"battr":[1,3,8,9,10,44]}}],"site":{"id":"56517","domain":"http://www.indiewire.com","page":"http://www.indiewire.com/","publisher":{"id":"56515"}},"device":{"ip":"107.77.100.84","ua":"Mozilla/5.0 (iPhone; CPU iPhone OS 8_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12D508 Safari/600.1.4","carrier":"AT&T Mobility LLC","language":"en-us","make":"Apple","model":"iPhone","os":"iOS","Osv":"8","osv":"8","js":1,"devicetype":1,"geo":{"country":"US"},"ext":{"res":"375x667","freq":0,"pf":2}},"user":{"ext":{"tmz":"-5"}},"badv":["18exgfs.com","gohookup.com"]}
    at org.apache.hadoop.hive.ql.exec.mr.ExecMapper.map(ExecMapper.java:195)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:54)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:430)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:342)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1594)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:163)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing writable {"id":"75F78BEC-29EA-4BD9-AFDE-59248A78D2E8","imp":[{"id":"1","tagid":"114140","banner":{"w":300,"h":250,"pos":3,"topframe":1,"battr":[1,3,8,9,10,44]}}],"site":{"id":"56517","domain":"http://www.indiewire.com","page":"http://www.indiewire.com/","publisher":{"id":"56515"}},"device":{"ip":"107.77.100.84","ua":"Mozilla/5.0 (iPhone; CPU iPhone OS 8_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12D508 Safari/600.1.4","carrier":"AT&T Mobility LLC","language":"en-us","make":"Apple","model":"iPhone","os":"iOS","Osv":"8","osv":"8","js":1,"devicetype":1,"geo":{"country":"US"},"ext":{"res":"375x667","freq":0,"pf":2}},"user":{"ext":{"tmz":"-5"}},"badv":["18exgfs.com","gohookup.com"]}
    at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:534)
    at org.apache.hadoop.hive.ql.exec.mr.ExecMapper.map(ExecMapper.java:177)
    ... 8 more
Caused by: org.apache.hadoop.hive.serde2.SerDeException: Row is not a valid JSON Object - JSONException: Duplicate key "osv"
    at org.openx.data.jsonserde.JsonSerDe.onMalformedJson(JsonSerDe.java:397)
    at org.openx.data.jsonserde.JsonSerDe.deserialize(JsonSerDe.java:174)
    at org.apache.hadoop.hive.ql.exec.MapOperator$MapOpCtx.readRow(MapOperator.java:154)
    at org.apache.hadoop.hive.ql.exec.MapOperator$MapOpCtx.access$200(MapOperator.java:127)
    at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:509)
    ... 9 more

**Comment by rcongiu** [comment] 2015-03-23 20:43
SerDe has the feature of 'mapping' a json field to another hive column name, but for JSON I used a library, I didn't realize it was case insensitive...I'd have to look into it.I think the best, more general solution is to have the underlying json library to be case sensitive, and then have the user place mappings for duplicate keys. -------------------------------------------------------
"Good judgment comes from experience. 
Experience comes from bad judgment"
------------------------------------------------------- 


     On Monday, March 23, 2015 1:35 PM, yongjiaw <notifications@github.com> wrote:
   

 I know Hive field names are case insensitive by SQL standard, so it makes sense to force all attribute names from the Json input data to lower case. However, JSON is really case sensitive, and a legal JSON input can be deemed illegal if using this SerDe. The following is an error trace from SerDeing an OpenRTB bid request in Json. The problem is that the Json data has "Osv":"8","osv":"8" twice, which is legal Json, but Hive won't be able to handle it - the only way right now is to ignore the data which is not ok for me. I don't know what should be the best solution, this is the clash between case-insensitive SQL and case sensitive Json. Would it be possible to have a SerDeProperty to only take the first value of the 'duplicate' attributes after case conversion? Or even better, is it possible to define something in the serde property so that the osv column is automatically converted to an array that can hold more than 1 values?Diagnostic Messages for this Task:
Error: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing writable {"id":"75F78BEC-29EA-4BD9-AFDE-59248A78D2E8","imp":[{"id":"1","tagid":"114140","banner":{"w":300,"h":250,"pos":3,"topframe":1,"battr":[1,3,8,9,10,44]}}],"site":{"id":"56517","domain":"http://www.indiewire.com","page":"http://www.indiewire.com/","publisher":{"id":"56515"}},"device":{"ip":"107.77.100.84","ua":"Mozilla/5.0 (iPhone; CPU iPhone OS 8_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12D508 Safari/600.1.4","carrier":"AT&T Mobility LLC","language":"en-us","make":"Apple","model":"iPhone","os":"iOS","Osv":"8","osv":"8","js":1,"devicetype":1,"geo":{"country":"US"},"ext":{"res":"375x667","freq":0,"pf":2}},"user":{"ext":{"tmz" :"-5"}},"badv":["18exgfs.com","gohookup.com"]}
 at org.apache.hadoop.hive.ql.exec.mr.ExecMapper.map(ExecMapper.java:195)
 at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:54)
 at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:430)
 at org.apache.hadoop.mapred.MapTask.run(MapTask.java:342)
 at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAs(Subject.java:415)
 at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1594)
 at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:163)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing writable {"id":"75F78BEC-29EA-4BD9-AFDE-59248A78D2E8","imp":[{"id":"1","tagid":"114140","banner":{"w":300,"h":250,"pos":3,"topframe":1,"battr":[1,3,8,9,10,44]}}],"site":{"id":"56517","domain":"http://www.indiewire.com","page":"http://www.indiewire.com/","publisher":{"id":"56515"}},"device":{"ip":"107.77.100.84","ua":"Mozilla/5.0 (iPhone; CPU iPhone OS 8_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12D508 Safari/600.1.4","carrier":"AT&T Mobility LLC","language":"en-us","make":"Apple","model":"iPhone","os":"iOS","Osv":"8","osv":"8","js":1,"devicetype":1,"geo":{"country":"US"},"ext":{"res":"375x667","freq":0,"pf":2}},"user":{"ext":{"tmz":"-5"}},"badv":["18exgfs .com","gohookup.com"]}
 at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:534)
 at org.apache.hadoop.hive.ql.exec.mr.ExecMapper.map(ExecMapper.java:177)
 ... 8 more
Caused by: org.apache.hadoop.hive.serde2.SerDeException: Row is not a valid JSON Object - JSONException: Duplicate key "osv"
 at org.openx.data.jsonserde.JsonSerDe.onMalformedJson(JsonSerDe.java:397)
 at org.openx.data.jsonserde.JsonSerDe.deserialize(JsonSerDe.java:174)
 at org.apache.hadoop.hive.ql.exec.MapOperator$MapOpCtx.readRow(MapOperator.java:154)
 at org.apache.hadoop.hive.ql.exec.MapOperator$MapOpCtx.access$200(MapOperator.java:127)
 at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:509)
 ... 9 more—

**Comment by yongjiaw** [comment] 2015-03-24 00:13
Thanks for the quick response. I agree the general solution is to let user specify the mapping, something like WITH SERDEPROPERTIES ( "mapping.hive_osv1" = "device.osv", "mapping.hive_osv2" = "device.Osv"). Right now, it seems to only support mapping of top level names, and some extra syntax is needed to specify whether it's case sensitive for backward compatibility. It looks like quite some effort.

**Comment by yongjiaw** [comment] 2015-03-24 00:31
I actually found this Json SerDe working for my case. bit.ly/mRYaNB
It silently swallows the potential conflict and just presents one final value, which is good enough for me. I'm still looking forward to the general solution though :)
I also tried to invoke Hive's built-in Json parser, if there is any, by reading the entire json data as a single complex struct column, without specifying any SerDe jar. The thinking is the since struct type is Hive native, it must be able to support it. It doesn't report any error, however, it looks the loaded data is completely messed up. I wonder if it's because the built-in default behavior for json parsing is pretty bad.

**Comment by chaqke** [comment] 2015-06-11 19:11
+1

**Comment by yun-zhang** [comment] 2017-01-27 01:49
+1 I think JSON keys should definitely be case sensitive. Let user defining mappings may not be a good idea though, since the json field could be a map type in Hive, which is most likely used when user wouldn't know all the possible keys ahead...

**Comment by rcongiu** [comment] 2017-04-07 22:47
I just pushed some changes for case sensitivity, have a look at the code in the develop branch, committed for #156

**Closed by rcongiu** 2017-04-07 22:47 UTC

**Comment by NandhakumarSrinivasan** [comment] 2017-11-08 16:42
CREATE EXTERNAL TABLE  sandbox.event_log (
timestamp string,
version string,
logtimestamp string,
domain string,
path string,
desc string,
msg string
)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
WITH SERDEPROPERTIES
( "case.insensitive" = "false",
  "mapping.timestamp" = "@timestamp",
  "mapping.version" = "@version",
  "mapping.logtimestamp" = "@logtimestamp",
  "mapping.domain" = "Domain",
  "mapping.path" = "path",
  "mapping.desc" = "Message",
  "mapping.msg" = "message"
)
LOCATION '/user/psol/psol_sandbox/pet_audit_event_kafka/eventdate=2017-11-07/';

I get the err regarding case sensitivity.
Caused by: org.apache.hadoop.hive.serde2.SerDeException: Row is not a valid JSON Object - JSONException: Duplicate key "message.

I used json-serde-1.3.6-jar-with-dependencies.jar on CDH 5.

Please advice
