### ISSUE TITLE
Handling null value from map data.

### ISSUE THREAD

**Issue by jhsbeat** [rcongiu/Hive-JSON-Serde#120] opened 2015-10-26 04:53 UTC
We're using Hive-JSON-Serde to parse json data stored in **AWS S3**.
The log data is stored S3 as a **json** string in the form like below: 
```
{"a": "something", "b": null, "c": { "d": "something", "e": null } }
a : string
b : string
c : map<string, string>
```
The problem is that Hive-JSON-Serde recognize the value of the key "c['e']" as a **'null' string** not a **real null value**. It only occurs in nested objects not the first level key such as "b".
So the records are not shown in the results of a query such as `where c['e'] IS NULL` but are shown in the results of `where c['e'] = 'null'` or `b IS NULL`.
Is there any **recommendation** for handling this issue or any **plan** to improve the case of theses situation?

**Comment by rcongiu** [comment] 2015-10-26 06:10
That's odd. Let me have a look.

**Comment by rcongiu** [comment] 2015-10-26 07:04
I had a quick look and added a unit test but I wasn't able to reproduce the problem. Are you sure that the JSON isn't "e":"null" rather than "e":null ? (null between double quotes).

**Comment by jhsbeat** [comment] 2015-10-26 07:17
@rcongiu Yes. null is not surrounded by quotes. Could you please let me know the version you have tests?

**Comment by rcongiu** [comment] 2015-10-31 17:31
I haven't checked them in yet... so, looking at the issue now, it looks to me that's actually not a bug of the SerDe, but it's a bug in the map serialization used by the console. 
So, the serde is correctly interpreting it as NULL, but when serializing to screen it looks like a string.
I tried what you said:
```
# data.txt 
# {"a": "something", "b": null, "c": { "d": "something", "e": null } }
drop table if exists json_test1;

create table json_test1 (
  a  string ,
  b  string , 
  c  map<string, string>
) ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
STORED AS TEXTFILE;

LOAD DATA LOCAL INPATH 'data.txt' OVERWRITE INTO TABLE  json_test1 ;
```

then 
```
hive> select * from json_test1;
OK
something	NULL	{"d":"something","e":"null"}

hive> select c from json_test1 where a = a;
OK
{"d":"something","e":"null"}
```

BUT if you do
```
hive> select c['e'] from json_test1 ;
OK
NULL

hive> select * from json_test1 where c['e'] IS NULL;
OK
something	NULL	{"d":"something","e":"null"}
Time taken: 0.089 seconds, Fetched: 1 row(s)
```

Also, if you use create as select, you'll find nulls as it should be : 
```
hive> create table t1 as select a,b,c['d'],c['e'] from json_test1 ;
Total MapReduce CPU Time Spent: 0 msec
OK
hive> select * from t1;
OK
something	NULL	something	NULL
```
So it looks to me it's the code that outputs maps to console that gets confused.
I am looking for where this happens in hive's source code.

**Comment by rcongiu** [comment] 2015-10-31 17:34
Also, I tried what you said:
> So the records are not shown in the results of a query such as where c['e'] IS NULL but are shown in the results of where c['e'] = 'null' or b IS NULL.

but I am not seeing that behavior:
```
hive> select * from json_test1 where c['e'] IS NULL;
OK
something	NULL	{"d":"something","e":"null"}
Time taken: 0.276 seconds, Fetched: 1 row(s)
hive> select * from json_test1 where c['e'] = 'null';
OK

```

**Comment by rcongiu** [comment] 2015-10-31 17:35
Closing since it does not appear to be a serde bug, but feel free to reopen if I am wrong.

**Closed by rcongiu** 2015-10-31 17:35 UTC

**Comment by rcongiu** [comment] 2015-10-31 18:02
I even tried to load the data in a parquet table and it yields the same results so it's definitely an issue in hive's default handling...it looks to be in the LazySimpleSerDe that's used by default (https://github.com/apache/hive/blob/master/serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazySimpleSerDe.java)

**Comment by nthumu** [comment] 2019-04-23 19:51
> e

Were you able to resolve this issue.

**Comment by nthumu** [comment] 2019-04-23 19:52
> We're using Hive-JSON-Serde to parse json data stored in **AWS S3**.
> The log data is stored S3 as a **json** string in the form like below:
> 
> ```
> {"a": "something", "b": null, "c": { "d": "something", "e": null } }
> a : string
> b : string
> c : map<string, string>
> ```
> The problem is that Hive-JSON-Serde recognize the value of the key "c['e']" as a **'null' string** not a **real null value**. It only occurs in nested objects not the first level key such as "b".
> So the records are not shown in the results of a query such as `where c['e'] IS NULL` but are shown in the results of `where c['e'] = 'null'` or `b IS NULL`.
> Is there any **recommendation** for handling this issue or any **plan** to improve the case of theses situation?

Hi were you able to resolve this issue?

**Comment by rcongiu** [comment] 2019-04-23 23:43
As I stated before, I checked this out and it looks like you're using the default hive serde, not this one. What's the output of your 'show create table ' statement ?

**Comment by nthumu** [comment] 2019-04-24 00:17
Hi Output shows ROW FORMAT SERDE  as 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'

**Comment by rcongiu** [comment] 2019-04-24 03:54
Yeah, that means you are not using my serde but the default json serde. To fix it you have to recreate the table or create a new one that uses my serde.

**Comment by nthumu** [comment] 2019-04-24 14:21
Thanks Roberto, I will explain scenario in detail.
we are getting JSON documents with before and after snapshot. we load this in staging as json structure and processing to next layer where it is flattened. Do we need to use your serde in staging table creating or next layer where we are flattening it out. 

Thanks

**Comment by rcongiu** [comment] 2019-04-25 22:38
Yes, you need to use my serde as it handles this situation correctly,
unlike the default serde.
