### ISSUE TITLE
Can not parse a multiline JSON document

### ISSUE THREAD

**Issue by csucla2015** [rcongiu/Hive-JSON-Serde#75] opened 2014-07-21 17:38 UTC
Hello,
Firstly thank you so much for making this open source.
I have been using it and it works well.
I ran into some issues currently.
So I am doing some twitter hash tag analysis for fun and have 10000 JSON files(Each being representative of a tweet).
It is a multiline JSON doc. 
Everytime I try to parse it using the Serde I get the following error. 

Failed with exception java.io.IOException:org.apache.hadoop.hive.serde2.SerDeException: Row is not a valid JSON Object
- JSONException: A JSONObject text must end with '}' at 26 [character 27 line 1]

I would really really appreciate some feedback/comments as to how can i get this done.

**Comment by antojoe** [comment] 2015-12-31 15:12
Thanks rcongiu.
Is that possible to parse a multi-line JSON document now with any latest piece of code. Do please share some details, if you have.

**Comment by nickandrew** [comment] 2016-12-06 00:39
> that would kind of go against hadoop design (splittable files are good, unsplittable bad).

Does Hadoop design also require the system to be inflexible and fail on valid JSON files, as newline is a valid whitespace character in JSON?

**Comment by rcongiu** [comment] 2016-12-06 01:22
Yes, if the file is not splittable, you have no reason to use hadoop.

**Comment by nickandrew** [comment] 2016-12-06 01:52
Actually, those are orthogonal concerns. I *must* use Hadoop, and I have over 800,000 JSON files to process, but I *do not* control the format of the input JSON files.

**Comment by dblock** [comment] 2017-04-03 22:21
I think this should be closed "by design". This is a Hadoop limitation and there's nothing that the SerDe can do about it. For the OP, the documents should be processed into 1 JSON per line and everything will work.

**Comment by nickandrew** [comment] 2017-04-04 01:49
Why do you think this is a Hadoop limitation? Splitting an input file into chunks is the responsibility of the SerDE and there's nothing in Hadoop that says it must be split at a line break and cannot be split between documents.

**Comment by dblock** [comment] 2017-04-04 11:59
I guess I should take this back, it's a limitation of the TEXTFILE storage.

If I understand this correctly hive splits data stored as TEXTFILE by a delimiter and feeds it to the deserializer, piece-by-piece, so if you're going to use a `\n` delimiter you're going to get back partial chunks. Furthermore if you store JSON documents in parts (we do and you should), they will be evenly distributed across nodes in a reduce operation, avoiding a lot of locking.

It does look like you can write a different [StorageHandler](https://cwiki.apache.org/confluence/display/Hive/StorageHandlers) or define separately how files are input or output, like the [MongoDB BSON SerDe](https://github.com/mongodb/mongo-hadoop) to overcome this limitation.

Please note that  am no expert, so definitely correct me if I am wrong.

**Comment by rcongiu** [comment] 2017-04-05 20:45
Closing as it's a well understood and known limitation

**Closed by rcongiu** 2017-04-05 20:45 UTC
