### ISSUE TITLE
Hive w/ Json Serde returns zero records for partitioned tables

### ISSUE THREAD

**Issue by jlerm** [rcongiu/Hive-JSON-Serde#38] opened 2013-09-21 21:19 UTC
I wonder if anyone ever tried rcongiu's Json Serde to define an external table on a partitioned Hive table.

If I define a non-partitioned external table setting the location to one of the partition folders, then it returns records as expected (for that single partition, of course).

However, if I set the parent folder for all partitions as the location for the partitioned external table, zero rows are returned.

By setting enabling DEBUG on the hive shell command line, I can see that the job reports a single path to be processed, which in turn results in zero map tasks.

If I define a partitioned table that sees the entire record as a single string column, then it fetches records from the partitions without a problem.

Any ideas?

Thanks,

Julius

**Comment by d-robin** [comment] 2016-09-08 16:20
On the same boat. Can this be really done?
Have you guys been able to do so?

**Comment by rcongiu** [comment] 2017-04-07 23:13
With partitions on external tables, data won't be loaded until you tell hive to load them.

Have you issued 
`MSCK REPAIR TABLE table_name;` (or `ALTER TABLE table_name RECOVER PARTITIONS` in Amazon EMR) ?

**Comment by rcongiu** [comment] 2017-04-07 23:17
I tested it and it works fine. It seems the issue is only that you forgot to tell hive to load the partitions. Closing.

**Closed by rcongiu** 2017-04-07 23:17 UTC
