### ISSUE TITLE
handle \n linebreaks

### ISSUE THREAD

**Issue by billou2k** [rcongiu/Hive-JSON-Serde#33] opened 2013-08-07 16:32 UTC
Hi,
Your SerDe does a great job thanks! 
The option to ignore malformed json is also pretty useful.
Most of the time it works fine, but in some cases the content has some \n characters in strings and Hive just doesn't handle that well at all, creating null rows everytime it sees a \n..
is there an existing property to fix this?

Thanks!

**Comment by pike007** [comment] 2016-04-21 10:39
@rcongiu Could you please guide me how to fix this
whenever it is reading \n in a single record it is splitting that record and giving me 2 two records

**Comment by rcongiu** [comment] 2016-04-21 20:33
The SerDe only works if there's one record per line.

**Comment by dblock** [comment] 2017-04-03 22:24
This is by design and should be closed.

**Comment by rcongiu** [comment] 2017-04-07 23:08
Agree, closing.

**Closed by rcongiu** 2017-04-07 23:08 UTC
