### ISSUE TITLE
Error creating table with Json schema

### ISSUE THREAD

**Issue by lakshminarayanar** [rcongiu/Hive-JSON-Serde#109] opened 2015-08-02 17:36 UTC
`Hive 0.14, Hadoop 2.6, Hive-Hcatalog 0.14.0`
I followed the instructions from [Here](http://hortonworks.com/blog/howto-use-hive-to-sqlize-your-own-tweets-part-two-loading-hive-sql-queries/) to create schema of json tweets data.
Created schema as per my tweets data and next got `json-serde-1.3.1-SNAPSHOT-jar-with-dependencies.jar` file as well.
Next tried creating table, it is throwing the following exception message:

`FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. org.apache.hadoop.hive.serde2.objectinspector.primitive.AbstractPrimitiveJavaObjectInspector.<init>(Lorg/apache/hadoop/hive/serde2/objectinspector/primitive/PrimitiveObjectInspectorUtils$PrimitiveTypeEntry;)V`

Next i tried creating a table without complex data types and got the following error: 

`hive> CREATE EXTERNAL TABLE  self_tweets (
    >    created_at string,
    >    id bigint,
    >    id_str binary,
    >    in_reply_to_screen_name string,
    >    in_reply_to_status_id bigint,
    >    in_reply_to_status_id_str binary,
    >    in_reply_to_user_id bigint,
    >    in_reply_to_user_id_str string,
    >    source string,
    >    text string
    >   )
    > ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
    > STORED AS TEXTFILE;
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Could not initialize class org.openx.data.jsonserde.objectinspector.JsonObjectInspectorFactory`

But the same is working with JsonSerDe of hcatalog as follows:

`hive>
    > CREATE EXTERNAL TABLE  self_tweets (
    >    created_at string,
    >    id bigint,
    >    id_str binary,
    >    in_reply_to_screen_name string,
    >    in_reply_to_status_id bigint,
    >    in_reply_to_status_id_str binary,
    >    in_reply_to_user_id bigint,
    >    in_reply_to_user_id_str string,
    >    source string,
    >    text string
    >   )
    > ROW FORMAT SERDE 'org.apache.hive.hcatalog.data.JsonSerDe'
    > LOCATION '/user/hue/practice/input/tweets/';
OK
Time taken: 1.432 seconds`

Please fix this issue earliest. And array or struct with empty throwing NullpointereException.
Please let me know whether it is a incompatible issue or any other ?

Thanks,
Lakshminarayana

**Comment by lakshminarayanar** [comment] 2015-08-03 15:11
Feature Request: need support for UNION data type #53  is still open.
So this jar doesn't support uniontype complex data type ? what version of this project jar compatible with hive and hadoop jars ?
Eagerly waiting for your reply.

Thanks,
Lakshminarayana

**Comment by rcongiu** [comment] 2017-04-07 22:56
UNION type was implemented. I see your table uses BINARY, which is not supported at the moment.

**Comment by rcongiu** [comment] 2017-04-07 23:07
If you create a table with the HCatalog serde with a binary field, you will still get an error if you do select *  since it does not support binaries either.

Closing as it's an expected behavior, and the other request (Union) was already implemented.

**Closed by rcongiu** 2017-04-07 23:07 UTC
